logging:
  config: src/main/resources/log4j2-local.yml

ng:
  service:
    properties:
      path: file:src/main/properties/ng-service.properties
  solace:
    properties:
      path: file:src/main/properties/solace.properties