server:
  port : 8085

spring:
  application:
    name: ngSolaceServices

logging:
  config: /etc/ng-screener/ng-solace/log4j2.yml

ng:
  service:
    properties:
      path: "file:/etc/ng-screener/ng-solace/ng-service.properties"
  solace:
    properties:
      path: "file:/etc/ng-screener/ng-solace/solace.properties"